### ISSUE TITLE
密码错误

### ISSUE THREAD

**Issue by k20028** [Limour-dev/daily_fudan_core#1]
如果密码出现 $ 等字符会出现错误

**Comment by Limour-dev** [comment]
> 如果密码出现 $ 等字符会出现错误

第一步 对密码进行base64编码
可以使用在线工具：https://tool.oschina.net/encrypt?type=3
如"我是奇怪的密码￥$PATH哈哈" 编码得到 "5oiR5piv5aWH5oCq55qE5a+G56CB77+lJFBBVEjlk4jlk4g="
第二步 将 "|||base64|||" 与得到的编码结果组合
如"|||base64|||5oiR5piv5aWH5oCq55qE5a+G56CB77+lJFBBVEjlk4jlk4g="
第三步 用组合结果替换掉原密码
如得到 “1930******* |||base64|||5oiR5piv5aWH5oCq55qE5a+G56CB77+lJFBBVEjlk4jlk4g= IYUU***** usr*** pwd***”
