### ISSUE TITLE
出现错误

### ISSUE THREAD

**Issue by k20028** [Limour-dev/daily_fudan_core#2]
![c8698056ddcde1d1e584ab332d0cd5f](https://user-images.githubusercontent.com/95536868/146738942-f70e5765-a994-4c8b-b5b1-6ca8aae7f844.jpg)

昨天还可以今天出现这个错误

**Comment by Limour-dev** [comment]
> ![c8698056ddcde1d1e584ab332d0cd5f](https://user-images.githubusercontent.com/95536868/146738942-f70e5765-a994-4c8b-b5b1-6ca8aae7f844.jpg)
> 
> 昨天还可以今天出现这个错误

快识别（图鉴）的账户余额不足，请去个人中心充值
