### ISSUE TITLE
运行时间

### ISSUE THREAD

**Issue by SBDRBD** [Limour-dev/daily_fudan_core#3]
非常感谢您的脚本，想请问如何设置每天自动打卡的时间？

**Comment by Limour-dev** [comment]
https://github.com/Limourli-liu/daily_fudan/wiki#q2how-to-use-my-own-schedule
![image](https://user-images.githubusercontent.com/93720049/148033673-fd722cb7-1051-45cb-b12d-3cfbaf605f67.png)

**Comment by SBDRBD** [comment]
谢谢！
