### ISSUE TITLE
运行成功但是没有任何效果

### ISSUE THREAD

**Issue by SBDRBD** [Limour-dev/daily_fudan_core#4]
运行显示成功，但是去查看系统并没有填报。我试了一下故意写错密码发现居然也能运行成功，也没有任何错误提示。我的FUDAN的value里面已经包括了token和快识别的账户密码，确认过都没有错。不知道为什么运行成功但是就是没有任何反应？需要Fork那个daily_fudan_core吗

**Comment by Limour-dev** [comment]
FUDAN需要大写

**Comment by Limour-dev** [comment]
![Uploading Screenshot_20220105_000911_com.android.chrome.png…]()

**Comment by Limour-dev** [comment]
![Screenshot_20220105_000911_com android chrome](https://user-images.githubusercontent.com/93720049/148088617-30245f58-c475-4b61-88b8-0704db8bbd77.png)

**Comment by Limour-dev** [comment]
不需要fork daily_fudan_core，所有操作都在daily_fudan_action这个仓库下进行

**Comment by Limour-dev** [comment]
![Screenshot_20220105_001212_com android chrome](https://user-images.githubusercontent.com/93720049/148089052-ec22acea-a32f-455f-b4f9-b6c5b3997ac0.png)
看了日志，显示no arg，说明secrets的名字写错了

**Comment by Limour-dev** [comment]
![Screenshot_20220105_001913_com tencent mm](https://user-images.githubusercontent.com/93720049/148090058-6a4e1dc8-76f8-4131-b513-a03ed3a503a7.png)
每天只有收到此消息才说明填写成功，收不到消息一律为填写失败。

**Comment by SBDRBD** [comment]
感谢！现在已经成功了。发现原来是我的secret值填错位置了，之前填到了那个action的bot那里，现在改正后就可以了，谢谢指正。
