### ISSUE TITLE
设定好secrets后，仍出现了拉取信息的bug和webVpn的bug

### ISSUE THREAD

**Issue by EricQi7** [Limour-dev/daily_fudan_core#7]
按照readme格式，设置好了secret1（用户 + 密码 + token + 图片识别用户 + 图片识别密码）和secret2（GH_PAT）。
出现了两种bug：
bug1:
“
File "/home/runner/work/daily_fudan_actions/daily_fudan_actions/./dailyFudan.py", line 166, in check
    logging.info("上一次提交日期为: %s " % last_info["d"]["info"]["date"])
TypeError: 'bool' object is not subscriptable
”
        打印日志的时候，last_info是bool类型，打印日志失败，推测可能是从网站（https://zlapp.fudan.edu.cn/ncov/wap/fudan/get-info）拉取上次打卡信息失败。我在浏览器直接访问该网站时，输入复旦学生账号密码就能拉取，所以怀疑是否是自己输入的账号密码输错了，但是仔细检查过，发现没输错，所以就不知道该如何解决了。
       并且在老版本平安复旦（已停止维护版本）上也遇到bug1的错误，老版本平安复旦打卡只有bug1的错误。

bug2:
“
File "/home/runner/work/daily_fudan_actions/daily_fudan_actions/FDU_WebVPN.py", line 189, in logout
    expire += self.get(self.logout_url).headers.get('Set-Cookie')
TypeError: unsupported operand type(s) for +=: 'NoneType' and 'str'
”
     这个bug是webVpn里提到的bug吗？

<img width="1272" alt="截屏2022-04-24 下午1 24 09" src="https://user-images.githubusercontent.com/50576531/164958046-dcb01bc4-ef2c-438d-ad26-abe3aee28e9b.png">
<img width="1252" alt="截屏2022-04-24 下午1 24 38" src="https://user-images.githubusercontent.com/50576531/164958047-31ecefd0-9650-4b0a-b5b8-5fc77f635dce.png">
<img width="1263" alt="截屏2022-04-24 下午1 24 48" src="https://user-images.githubusercontent.com/50576531/164958048-4d76d3e2-6f94-4f3f-b6b0-f617004454be.png">

**Comment by Limour-dev** [comment]
bug2是WebVPN的问题，目前登不上了，得等信息办老师修复

**Comment by Limour-dev** [comment]
bug1的话，是不是昨天没填平安复旦呀，这个脚本获取昨天的填写信息失败了

**Comment by Limour-dev** [comment]
> 按照readme格式，设置好了secret1（用户 + 密码 + token + 图片识别用户 + 图片识别密码）和secret2（GH_PAT）。 出现了两种bug： bug1: “ File "/home/runner/work/daily_fudan_actions/daily_fudan_actions/./dailyFudan.py", line 166, in check logging.info("上一次提交日期为: %s " % last_info["d"]["info"]["date"]) TypeError: 'bool' object is not subscriptable ” 打印日志的时候，last_info是bool类型，打印日志失败，推测可能是从网站（[https://zlapp.fudan.edu.cn/ncov/wap/fudan/get-info）拉取上次打卡信息失败。我在浏览器直接访问该网站时，输入复旦学生账号密码就能拉取，所以怀疑是否是自己输入的账号密码输错了，但是仔细检查过，发现没输错，所以就不知道该如何解决了。](https://zlapp.fudan.edu.cn/ncov/wap/fudan/get-info%EF%BC%89%E6%8B%89%E5%8F%96%E4%B8%8A%E6%AC%A1%E6%89%93%E5%8D%A1%E4%BF%A1%E6%81%AF%E5%A4%B1%E8%B4%A5%E3%80%82%E6%88%91%E5%9C%A8%E6%B5%8F%E8%A7%88%E5%99%A8%E7%9B%B4%E6%8E%A5%E8%AE%BF%E9%97%AE%E8%AF%A5%E7%BD%91%E7%AB%99%E6%97%B6%EF%BC%8C%E8%BE%93%E5%85%A5%E5%A4%8D%E6%97%A6%E5%AD%A6%E7%94%9F%E8%B4%A6%E5%8F%B7%E5%AF%86%E7%A0%81%E5%B0%B1%E8%83%BD%E6%8B%89%E5%8F%96%EF%BC%8C%E6%89%80%E4%BB%A5%E6%80%80%E7%96%91%E6%98%AF%E5%90%A6%E6%98%AF%E8%87%AA%E5%B7%B1%E8%BE%93%E5%85%A5%E7%9A%84%E8%B4%A6%E5%8F%B7%E5%AF%86%E7%A0%81%E8%BE%93%E9%94%99%E4%BA%86%EF%BC%8C%E4%BD%86%E6%98%AF%E4%BB%94%E7%BB%86%E6%A3%80%E6%9F%A5%E8%BF%87%EF%BC%8C%E5%8F%91%E7%8E%B0%E6%B2%A1%E8%BE%93%E9%94%99%EF%BC%8C%E6%89%80%E4%BB%A5%E5%B0%B1%E4%B8%8D%E7%9F%A5%E9%81%93%E8%AF%A5%E5%A6%82%E4%BD%95%E8%A7%A3%E5%86%B3%E4%BA%86%E3%80%82) 并且在老版本平安复旦（已停止维护版本）上也遇到bug1的错误，老版本平安复旦打卡只有bug1的错误。
> 
> bug2: “ File "/home/runner/work/daily_fudan_actions/daily_fudan_actions/FDU_WebVPN.py", line 189, in logout expire += self.get(self.logout_url).headers.get('Set-Cookie') TypeError: unsupported operand type(s) for +=: 'NoneType' and 'str' ” 这个bug是webVpn里提到的bug吗？
> 
> <img alt="截屏2022-04-24 下午1 24 09" width="1272" src="https://user-images.githubusercontent.com/50576531/164958046-dcb01bc4-ef2c-438d-ad26-abe3aee28e9b.png">
> 
> <img alt="截屏2022-04-24 下午1 24 38" width="1252" src="https://user-images.githubusercontent.com/50576531/164958047-31ecefd0-9650-4b0a-b5b8-5fc77f635dce.png">
> 
> <img alt="截屏2022-04-24 下午1 24 48" width="1263" src="https://user-images.githubusercontent.com/50576531/164958048-4d76d3e2-6f94-4f3f-b6b0-f617004454be.png">

以上

**Comment by EricQi7** [comment]
是的！！！之前一直用的老的平安复旦打卡程序，昨天失效之后就漏打卡了，难怪今天拉取信息不成功。我以为拉取的是上次打卡的信息。谢谢up！

**Comment by EricQi7** [comment]
是的！！！之前一直用的老的平安复旦打卡程序，昨天失效之后就漏打卡了，难怪今天拉取信息不成功。我以为拉取的是上次打卡的信息。谢谢up！

**Comment by EricQi7** [comment]
是的！！！之前一直用的老的平安复旦打卡程序，昨天失效之后就漏打卡了，难怪今天拉取信息不成功。我以为拉取的是上次打卡的信息。谢谢up！
